FROM node:20-alpine

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    gcc \
    libc-dev \
    ffmpeg \
    opus \
    opus-dev \
    libogg \
    libogg-dev \
    build-base

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .

CMD ["node", "index.js"]
