services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - api
    env_file:
      - .env

volumes:
  mongo_data:
