FROM node:20-alpine
RUN apk add --no-cache \
    ffmpeg \
    opus \
    opus-dev \
    libogg \
    libogg-dev \
    build-base
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
CMD ["node", "index.js"]
